version: '2'
services:
    starkev2-app:
        image: starkev2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://starkev2-postgresql:5432/starkev2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    starkev2-postgresql:
        extends:
            file: postgresql.yml
            service: starkev2-postgresql
